version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nt8r05bu3c5u"
s3_prefix = "lambda-example"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"hello-world-typescript-lambda\""
image_repositories = []
