version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "us-east-2"
parameter_overrides = "AppName=\"location-image-greating\""
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hxbb2nawd7x0"
s3_prefix = "sam-app"
capabilities = "CAPABILITY_IAM"
image_repositories = ["LambdaFunction=658068096501.dkr.ecr.us-east-2.amazonaws.com/samapp7427b055/lambdafunctiondfe28c74repo"]
