name: Deploy to lambda
on: [push]
jobs:
  deploy:
    name: Build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install, test and build
        run: |
          yarn
          yarn CI

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/setup-sam@v1

      # Build inside Docker containers
      - run: sam build --use-container --container-env-var IP_REGISTRY_API_KEY=${{ secrets.IP_REGISTRY_API_KEY }} --container-env-var IP_REGISTRY_DOMAIN=${{ secrets.IP_REGISTRY_DOMAIN }}
      # Prevent prompts and failure when the stack is unchanged
      - run: sam deploy 


